### ISSUE TITLE
当需要懒加载的元素页面刷新时rect.top 就小于0，不会自动加载

### ISSUE THREAD

**Issue by fsy0718** [barretlee/lazyload#1]
![1](https://cloud.githubusercontent.com/assets/3926479/11231877/abad375e-8de7-11e5-8e86-49805637abe2.png)
当用户打开页面，滑动滚动条，然后F5刷新页面，就会出现这种情况
- 在`loadItem`的判断条件中加入 `rect.top < 0 && (rect.top + rect.height) >= this.DISTANCE`
- 在`loadItem`中增加所有图片加载完成的回调函数

**Comment by barretlee** [comment]
嗯，这是一个十分简洁的 lazyload 组件，考虑的很多都不周全，不过你提的建议很合理，我回头加上去。

**Comment by barretlee** [comment]
Updated https://github.com/barretlee/lazyload/commit/7b680b067b93c27bdf5b6c894afce9008a16791b
