### ISSUE TITLE
关于代码的一些疑问

### ISSUE THREAD

**Issue by lucien925** [barretlee/lazyload#8]
你好，胡子哥。我在看你的`$()`函数，发现你使用了一句`sheet.addRule(query, "a:b")`，然后获取到`document.all`后判断当前的元素是否有`a`属性，再将有a属性的添加到结果数组中，我想请问下，这样做的原理是什么呢？  
如果可以的话，请稍加点拨下，谢谢啦。

**Comment by barretlee** [comment]
这是浏览器提供的基本 API。

**Comment by lucien925** [comment]
@barretlee   我使用了你的方法在各个浏览器的版本中测试，但是没发现判断`item.currentStyle.a`会输出结果，在chrome和firefox下报错，在低版本的IE下输出undefined;

**Comment by lucien925** [comment]
是我错了  sorry ！  我现在测试在IE9下至少是OK的 。

**Comment by barretlee** [comment]
你 google 搜索下 IE 操作 style 的方法。我写的代码有可能有问题，找到正确方法了，告诉我下；）

我比较懒，哈哈~

**Comment by lucien925** [comment]
好的，我在测试。
